### PR TITLE
Theme Changes

### PR DESCRIPTION
**Pull request by Iamlooker**
Added Some Themes

### CODE REVIEW

**Comment by Iamlooker** [comment]
wait I will make changes to it to save it

**Comment by dihak** [comment]
Hi, thanks for your contribution., i have checked., but it not finished yet., i think it must be nicer when you create new branch before create a pull request 😁

**Comment by Iamlooker** [comment]
Thank you bro for the feed back I would love to hear your ideas on what could be polish and improved

**Comment by dihak** [comment]
I have checked your app., it's cool, but not finished yet., i will merge it after finish

**Pull request closed without merging**
