### PR TITLE
Fixed some more translations and some Design Changes

### PR DESCRIPTION
**Pull request by Iamlooker**
I have tried building the app on my side its working fine 
Can you also check

### CODE REVIEW

**Comment by Iamlooker** [comment]
And sir I would love to know 
How you made that readme screenshot 
So I can update it too

**Comment by Iamlooker** [comment]
And m working on themeing
Some work is done
Only Dark themed one is also ready, but I am not good enough to make switchable themes right now
Would you like me to send the pull request of dark theme seperately

**Comment by dihak** [comment]
> And sir I would love to know
> How you made that readme screenshot
> So I can update it too

i using figma to create a screenshot

**Comment by dihak** [comment]
> And m working on themeing
> Some work is done
> Only Dark themed one is also ready, but I am not good enough to make switchable themes right now
> Would you like me to send the pull request of dark theme seperately

I think you must add settings feature, before create a Pull Request

User can change dark mode and normal mode by their choice, thats will be ok

**Comment by Iamlooker** [comment]
Sir can I send you the new apk via whatsapp if you dont mind

**Comment by Iamlooker** [comment]
Bro I added dynamic theme ...
Buts its on wrong page😜
Bad thing is I am exhausted😢

**Comment by dihak** [comment]
Nice, can i look at them? I will help you 😁

**Pull request merged**
