### PR TITLE
Added remove habit button to the top right corner of detailed view.

### PR DESCRIPTION
**Pull request by sdheer**
Added remove habit button to the top right corner of detailed view. One thing i noticed in the detailed view is the accessibility and visibility of the delete/remove task button.

### CODE REVIEW

**Comment by dihak** [comment]
Can you share the screenshot?

**Comment by sdheer** [comment]
> Added remove habit button to the top right corner of detailed view. One thing i noticed in the detailed view is the accessibility and visibility of the delete/remove task button.



> Can you share the screenshot?

Screenshot_1728615402

**Comment by dihak** [comment]
I think it would be better if the delete button was on the left side of edit. And the delete button at the bottom must be removed. I appreciate your time and effort for your contribution, thank you.

**Comment by sdheer** [comment]
Done
Screenshot_1728707172
Screenshot_1728707177

**Review by dihak — APPROVED** [review]

**Comment by dihak** [comment]
Thank you for your contribution 😁

**Pull request merged**
